version: "2.4"

services:
  sender:
    image: $SENDER
    container_name: sender
    hostname: sender
    #stdin_open: true
    #tty: true
    #entrypoint: /bin/bash
    volumes:
      - ./$INPUT:/input:ro
    environment:
      - ROLE=sender
      - QLOGDIR=/logs/qlog
      - RTPLOGDIR=/logs/rtp
      - CCLOGFILE=/logs/cc.log
      - LOG_FILE=/logs/qrt.log
      - STREAMLOGFILE=/logs/stream.log
      - RECEIVER=receiver:4242
      - VIDEOS=$VIDEOS
      - SENDER_PARAMS=$SENDER_PARAMS
    cap_add:
      - NET_ADMIN

  receiver:
    image: $RECEIVER
    container_name: receiver
    hostname: receiver
    #stdin_open: true
    #tty: true
    #entrypoint: /bin/bash
    volumes:
      - $OUTPUT:/streams
    environment:
      - ROLE=receiver
      - QLOGDIR=/logs/qlog
      - RTPLOGDIR=/logs/rtp
      - LOG_FILE=/logs/qrt.log
      - STREAMLOGFILE=/logs/stream.log
      - DESTINATION=/streams/out.mkv
      - RECEIVER_PARAMS=$RECEIVER_PARAMS
    cap_add:
      - NET_ADMIN

